volumes:
  db-data:
  nginx-certs:

services:
  mysql:
    image: mysql:5.7
    container_name: prestashop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      # Optional: seed database on first run (put dump .sql or .sql.gz into ./db/init)
      - ./db/init:/docker-entrypoint-initdb.d:ro

  prestashop-git:
    build:
      dockerfile: .docker/Dockerfile
      context: .
      args:
        - VERSION=${VERSION:-7.4}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - NODE_VERSION=${NODE_VERSION:-14.21.3}
    container_name: prestashop
    environment:
      PS_INSTALL_AUTO: 1
      PS_HANDLE_DYNAMIC_DOMAIN: 0
      DB_USER: root
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: mysql
      DB_PREFIX: ps_
      PS_DOMAIN: localhost
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
      PS_COUNTRY: pl
      PS_LANGUAGE: pl
      PS_DEV_MODE: 1
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: prestashop_demo
    command: ["/tmp/wait-for-it.sh","--timeout=60","--strict","mysql:3306","--","/tmp/docker_run_git.sh"]
    depends_on:
      - mysql
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/var/www/html/:delegated
      - ./apache-conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-conf/ssl:/etc/ssl/certs
      - ./apache-conf/mods/ssl.load:/etc/apache2/mods-enabled/ssl.load:ro
      - ./apache-conf/mods/socache_shmcb.load:/etc/apache2/mods-enabled/socache_shmcb.load:ro
      - ./apache-conf/mods/rewrite.load:/etc/apache2/mods-enabled/rewrite.load:ro
